# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76d980ebec68588986fb5f1c4f0fbc11b684e1a2e564a771fd209b0029594b5ab613c1ed05af58e3735089850f8ba1452ae40750f1abecdfc4e8360f10e74853

test:
  secret_key_base: 715113de223e39c5b6f48f722b615461647a5fc3264791a148a840200d28587346f514202cdc5b71d13e729883adff326e1cc40e1dba427031270a412e643107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
